# 🧱 Nazwa workflowa – pojawi się w zakładce „Actions” w Twoim repozytorium
name: Deploy Vite app to GitHub Pages

# 🚀 Określamy, kiedy uruchamiać ten workflow:
# tutaj: przy każdym pushu do gałęzi „main”
on:
  push:
    branches:
      - main

# 💼 Każdy workflow składa się z jednego lub wielu "jobs" (zadań)
jobs:
  build:
    # 🔧 Workflow uruchamia się na najnowszym Ubuntu (czyli serwerze z Linuxem)
    runs-on: ubuntu-latest

    # 📋 Lista kroków, które GitHub wykona po kolei
    steps:
      # 1️⃣ Pobierz kod źródłowy repozytorium z GitHuba
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Zainstaluj Node.js (środowisko do uruchamiania Vite i Reacta)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20   # użyj Node 20 – stabilna wersja zgodna z Vite

      # 3️⃣ Zainstaluj wszystkie zależności z package.json
      - name: Install dependencies
        run: npm ci           # „npm ci” jest szybsze i bardziej przewidywalne niż „npm install”

      # 4️⃣ Zbuduj projekt (Vite utworzy folder „dist”)
      - name: Build project
        run: npm run build

      # 5️⃣ Opublikuj folder „dist” jako stronę GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3   # popularna i sprawdzona akcja do publikowania
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # automatyczny token z uprawnieniami do repozytorium
          publish_dir: ./dist                         # katalog, który ma zostać opublikowany (czyli wynik budowy Vite)
